filebeat.inputs:
  - type: filestream
    id: batch-processing-json
    enabled: true
    paths:
      - /usr/share/filebeat/input/*.json
    parsers:
      - ndjson:
          overwrite_keys: true
          add_error_key: true
          target: ""

processors:
  - add_fields:
      target: service
      fields:
        name: batch-processing
  - add_tags:
      tags:
        - spring-batch
        - json

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: false
logging.to_syslog: false
